apiVersion: v1
kind: Service
metadata:
  name: leaderboard-api
  namespace: trade-eval
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector: { app: leaderboard-api }
  ports: [{ name: http, port: 80, targetPort: 8084 }]
