apiVersion: v1
kind: Service
metadata:
  name: {{ include "telemetry-ingester.fullname" . }}
  labels: {{- include "telemetry-ingester.labels" . | nindent 4 }}
spec:
  selector: { app: telemetry-ingester }
  ports: [{ port: {{ .Values.service.port }}, targetPort: {{ .Values.service.port }} }]
